### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by schacon** [progit/progit2-nl#1]
Atlas build system is throwing this:

> The following errors were encountered parsing the HTML files in this project: book/03-git-branching/1-git-branching.asc:782: parser error : attributes construct error

**Comment by Cpt-xx** [comment]
This parsing error has me baffled a bit, the file mentioned (1-git-branching.asc) doesn't even contain 782 lines, so it must be some underlying/referred to file. Is there a way into the actual log files so I can try and find out what file is in error so I can correct the situation?

**Comment by Cpt-xx** [comment]
Okay, so I've pushed my latest work up to the master, how can I see whether the issue you reported has been resolved by this? (and my original question still stands....)

**Comment by Cpt-xx** [comment]
Well... I haven't got an answer to my question, but the builds seem to go alright going by the PDFs I can get from the site.
