### ISSUE TITLE
English sentence in text

### ISSUE THREAD

**Issue by DeTommie** [progit/progit2-nl#4]
In chapter 7.11 Git Tools - Submodules there is still an English sentence present.  In section 'Beginnen met submodules' there is the following sentence 'This is how other people who clone this project know where to get the submodule projects from.'. The translated text is already written.

**Comment by Cpt-xx** [comment]
Thanks for pointing this issue out, I will make the correction directly.
Dank je voor het vinden van deze fout, ik zal direct de correctie uitvoeren.
