### ISSUE TITLE
Great work! Is there 1 PDF file download somewhere?

### ISSUE THREAD

**Issue by seansan** [progit/progit2-nl#6]
Great work! Is there 1 PDF file download somewhere?

I was looking at the link: https://git-scm.com/book/nl/v2 and I know I can build. But is there 1 1 file PDF download link somewhere? (thx)

Also the progit link on the frontpage does not exist anymore?

**Comment by Cpt-xx** [comment]
Thanks, and yes there is: https://git-scm.com/book/nl/v2.

I will try and sort this out one day, but as it doesn't appear in the book I won't be in a hurry to do so. If you could see if there is a replacement that would be great.

- Nederlandse tekst -

Dank je, en ja die is er: https://git-scm.com/book/nl/v2

Ik zal kijken of er een oplossing is, maar dat kan even duren daar het niet in het boek verschijnt. Als jij zou kunnen zien of er een vervanger is zou ik erg 'graatvol' zijn :).

- signature/krabbeltje -

Kind regards/Met vriendelijke groet,

Cor
